### ISSUE TITLE
wget vault712_server.sh returns 404

### ISSUE THREAD

**Issue by chikeichan** [BloddyBaron/Vault712#3]
The following installation command return 404

```sh
wget https://raw.githubusercontent.com/BloddyBaron/Vault712/master/vault712_server.sh
```

**Comment by BloddyBaron** [comment]
All files have been merged into the main file as a function since last commit https://github.com/BloddyBaron/Vault712/commit/96b052258660b540d02d9a5463d9a19173d2850b
